name: Dependency check builder
on:
  schedule:
    - cron:  '0 0 * * *' 
  workflow_dispatch:
    # Needed so we can run it manually
jobs:
  depcheck-builder:
    runs-on: ubuntu-latest
    name: Dependency_check_builder
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build latest images
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker build -t owasp/dependency-check-action:latest .
          docker push owasp/dependency-check-action:latest
      - name: Update Published Date
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          echo "Last Published: $(date)" > published.md
          git commit -am "published"
          git push origin main

